name: Towny
main: it.TownyGDR.TownyGDR
version: 1.0
author: Elsalamander
depends: []
api-version: 1.16
depend: [Library, Vault]
commands:
   Zona:
      usage: /<command>
     
   City:
      usage: /<command>